### PR TITLE
Fix issue #101, make valid tests for Dockerfile

### PR DESCRIPTION
**Pull request by nyanshak**
- Make new sample json file
- Add test files for filesystem tests for Dockerfile
- Change Dockerfile to install bash (dependency) and point to new checklist

### CODE REVIEW

**Comment by siddharthist** [comment]
I like what you did here! I'll test this ASAP, thanks for your contribution!

**Comment by siddharthist** [comment]
Looks like one test still fails, here's what I got:
```
INFO[0000] Creating checklist(s)...                      path=/gopath/src/github.com/CiscoCloud/distributive/samples/docker-alpine.json type=file
INFO[0000] Running checklist File                       
INFO[0000] Running checklist Directory                  
INFO[0000] Running checklist Symlink                    
INFO[0000] Running checklist checksum                   
INFO[0000] Running checklist checksum                   
INFO[0000] Running checklist FileMatches                
INFO[0000] Running checklist Permissions                
INFO[0000] Running checklist DiskUsage                  
INFO[0000] Report from checklist                         checklist=Filesystem checks report=↴
Total: 8
Passed: 7
Failed: 1
Other: 0
File did not have permissions: -rw-rw-rw-
```
And indeed, it doesn't on my system: 
```bash
$ ls -alh samples/files
total 16K
drwxr-xr-x 2 lb users 4.0K Oct 20 09:40 .
drwxr-xr-x 3 lb users 4.0K Oct 20 09:40 ..
-rw-r--r-- 1 lb users   46 Oct 20 09:40 checksum_testfile.txt
-rw-r--r-- 1 lb users    9 Oct 20 09:40 filesystem_regex_test.txt
lrwxrwxrwx 1 lb users   21 Oct 20 09:40 symlink_checksum_test.txt -> checksum_testfile.txt
```
Is there some way we could set the permissions in Docker, or perhaps just remove that check?

**Comment by nyanshak** [comment]
I updated with a new commit with filesystem.json using correct permissions (git doesn't preserve them). If you want to remove the check entirely, that's up to you. :+1:

**Comment by siddharthist** [comment]
That'll be fine, since I tried with a fresh clone. Thank you!

**Comment by siddharthist** [comment]
Works for me!

**Pull request merged**
